### PR TITLE
feat: care centre 

### PR DESCRIPTION
**Pull request by hraza01**
Added care centre capability according to the following issues:
- #131 
- #132 

Care Centre form:
2023-10-28 at 11 37 27@2x

Care Centre Admission form:
2023-10-28 at 11 35 09

I've added logic for the following scenarios:
- A beneficiary once admitted into a facility cannot be re-admitted in the same facility unless discharged first.
- Actual duration is calculated once the user sets the status to discharged, sets a discharge date, and saves the document.
- Work/tasks performed on the beneficiary cannot be before the admission date.
- Discharge date cannot be before the admission date.
- Beneficiary has to be discharged (status = discharged) before Care Centre Admission document can be submitted.
- Validated capacity to make sure there is enough capacity in a facility before a beneficiary is admitted.

Care Centre document has a virtual DocField that calculates vacant beds on the fly. I've also added 2 shortcuts to the changemakers workspace that lead to Care Centre and Care Centre Admission DocTypes.

I haven't run any unit tests yet, but will work on it after I get a response. 

Please let me know if something can be improved further. 

Thanks

### CODE REVIEW

**Comment by NagariaHussain** [comment]
@hraza01 can you please add screenshots of the forms to the PR description?

**Comment by hraza01** [comment]
@NagariaHussain Added screenshots now

**Comment by NagariaHussain** [comment]
@Nikhil-Jorge Can you please take a look at the forms?

**Comment by Nikhil-Jorge** [comment]
@hraza01 @NagariaHussain Looks Good. But I cant find it in staging - for testing.

Only 1 Addition - there need to be 3 Status : as Admitted, Hospitalised and Discharged.

'Hospitalised' is actually like admitted only. for 2 days or so - some beneficiaries might be in hospital but the but will be reserved. Rest looks fine. Let me know how can I see this in staging. Lets aim at deploying it  on 7th in Bangalore instance.

**Comment by hraza01** [comment]
@Nikhil-Jorge @NagariaHussain I've added the "Hospitalised" status in Care Centre Admission form now. It will also count towards bed capacity being reserved in a care centre.

2023-11-05 at 14 46 00@2x

**Pull request merged**
